### ISSUE TITLE
Unneeded binary in neat-gcc source distribution

### ISSUE THREAD

**Issue by mingodad** [Neat-Lang/neat#10]
I'm trying to build from a cloned repository and getting the above problems, downloading the https://github.com/Neat-Lang/neat/releases/download/v0.1.9/neat-v0.1.9-gcc.tar.xz then it builds, notice that there is a `src/main` binary there that when trying to execute gives this (on Ubuntu 18.04 64bits):
```
./main
./main: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./main)
```
Does that binary need to be there ?

_Originally posted by @mingodad in https://github.com/Neat-Lang/neat/issues/9#issuecomment-1254894292_

**Comment by FeepingCreature** [comment]
Issue fixed. Binary will be absent in the next release.

Now to see why gcc builds segfault now...
