### ISSUE TITLE
There's something fishy going on in HashMap_callMember

### ISSUE THREAD

**Issue by FeepingCreature** [Neat-Lang/neat#14]
Valgrind routinely sees reads before an allocation. They don't seem to be breaking the build though.

See https://github.com/Neat-Lang/neat/issues/12

**Comment by FeepingCreature** [comment]
Oh oops

apparently, it helps to _actually look_:

                locRange.assert(args.length == 1, "hashmap.allocate() expects one parameter, size")?;
                auto size = args[0].sym.compile(context)?.beExpressionImplCall(context, args[0].locRange)?;
                auto sizeT = expectImplicitConvertTo(context, size, context.nativeWordType, args[1].locRange)?;

> **args[1]**

fixed

**Comment by mingodad** [comment]
Repetition is the mother of several errors !
Why not use an intermediate/unique variable ?

**Comment by FeepingCreature** [comment]
Eh, what I really need is array range checking.
