### ISSUE TITLE
Array index out of bounds: 2

### ISSUE THREAD

**Issue by mingodad** [Neat-Lang/neat#16]
After a fresh gcc build from https://github.com/Neat-Lang/neat/releases/download/v0.2.1/neat-v0.2.1-gcc.tar.xz :
```
./neat
Array index out of bounds: 2
```

**Comment by FeepingCreature** [comment]
What? Oh, that's very strange. The compiler works fine, but the help page is broken.

If you call it with arguments, it should run.

**Comment by FeepingCreature** [comment]
Should be fixed on master.

**Comment by rofl0r** [comment]
e315c3e231d3cd05485355106215d2f7ded946e3
