### ISSUE TITLE
Confusing error caused by `return` without a semicolon

### ISSUE THREAD

**Issue by dbohdan** [Neat-Lang/neat#28]
Compiling the following code results in this error: "Assertion failed! Aborting." 

```d
module ret;

void main() {
    return
}
```

The problem with the code is that the semicolon is missing after the `return` statement, which does not have an argument. The code compiles without the semicolon when `return` has an argument.

```d
// Compiles.
module ret;

int main() {
    return 0
}
```

The compiler should say the error is due to invalid syntax.

Edit: Oops, I misdiagnosed the cause of the error at first. Fixed.

**Comment by FeepingCreature** [comment]
Thanks! Fixed.

It's a bit weird to parse because `return` is an expression, not a statement.

**Comment by FeepingCreature** [comment]
New error is:

```
hello.nt:3:
void main() { return }
                     ^ expression or semicolon expected
```
