### ISSUE TITLE
Gtkdemo not working

### ISSUE THREAD

**Issue by wilsonk** [Neat-Lang/neat#38]
I am getting this error when trying to build the gtkdemo:
```
/home/user/.cache/neat/git/https___github.com_neat-lang_gtk/v0.0.8/src/gtk.nt:75:
            .case(:none: ""));
                  ~~~~~~~~~ Type is not listed in Either!

```
Seems like the Neat-lang/gtk repo needs a small update, perhaps?

**Comment by FeepingCreature** [comment]
Augh I swear to god, I keep breaking that.

**Comment by FeepingCreature** [comment]
Fixed: it was already fixed, I just didn't use the current version of neat-gtk.
