### ISSUE TITLE
Symbol import quietly fails and does not introduce symbol binding if imported symbol isn't found

### ISSUE THREAD

**Issue by rsaarelm** [Neat-Lang/neat#50]
Consider this code in `string.nt`

```
int atoi(string s) {
    import neat.runtime : atoi;

    return atoi(s);
}
```

It imports a function with the same name as the function being written. Without the import statement, the function definition would be a recursive infinite loop.

If the imported symbol isn't found in the namespace, the import just silently fails and the function will turn into an infinite loop. Instead, the import statement should fail with a compilation error if the symbol is not found.

**Comment by FeepingCreature** [comment]
Fixed.
