### ISSUE TITLE
Compiling with `--unittest` activates stdlib unit tests as well, which might not be able to run for a local project

### ISSUE THREAD

**Issue by rsaarelm** [Neat-Lang/neat#51]
I try to run unit tests for my local project by doing

```
neat --unittest --no-main main.nt
./main.nt
```

and this fails with

```
(...path...)/neat-v0.7.0-gcc/src/std/file.nt:91:16: assertion failed: 'isRegularFile("build/neat")' was false
Assertion failed! Aborting.
```

Apparently it tries to run unit tests in the standard library code and these have requirements that aren't being met. Only unit tests in the local code being compiled should be run.

**Comment by FeepingCreature** [comment]
oh yeah this is fixed 0.7.1
