### ISSUE TITLE
Allow suppressing end-of-line newline in string literals with a trailing backslash

### ISSUE THREAD

**Issue by rsaarelm** [Neat-Lang/neat#66]
Same behavior [as in Rust](https://doc.rust-lang.org/stable/reference/tokens.html#string-literals).

```
print("xyzzy

plugh");
```

should be same as
```
print("\
xyzzy

plugh\
");
```

**Comment by FeepingCreature** [comment]
How's the indentation work on that?

**Comment by FeepingCreature** [comment]
> when an unescaped U+005C character (\) occurs immediately before a line break, then the line break character(s), and all immediately following (U+0020), \t (U+0009), \n (U+000A) and \r (U+0000D) characters are ignored

I'll probably not skip newlines there, since Rust call it out as confusing.

**Comment by FeepingCreature** [comment]
Implemented https://github.com/Neat-Lang/neat/commit/34d46aa7745b7cf506e9eefc28bbcc32f06d2520
