### ISSUE TITLE
Pointers are not type safe

### ISSUE THREAD

**Issue by ntrel** [Neat-Lang/neat#8]
From the struct test:

    void* mem = malloc(8);
    S* sp = mem;
    int* ip = mem;

sp and ip should require a cast.

**Comment by FeepingCreature** [comment]
This is deliberate, for exactly the reason that `void*` can represent "any pointer". S* does not implconv to int*, for instance. Though I can see the argument for requiring a cast.

**Comment by rofl0r** [comment]
> Though I can see the argument for requiring a cast.

me too, by having a C++ mindset instead of a C mindset. i myself belong to latter category, so not requiring a cast is preferable to me.

**Comment by ntrel** [comment]
@rofl0r 
> me too, by having a C++ mindset instead of a C mindset

Any language that is type safe will not allow an untyped pointer to convert to a typed pointer. So it's not just C++ that does this.

**Comment by ntrel** [comment]
> void* can represent "any pointer"

Yes, so implicitly converting from `T*` *to* `void*` is fine. `T*` cannot represent any pointer, so `void*` should not implicitly convert to `T*`.

**Comment by FeepingCreature** [comment]
I think packages (Neat's import path replacement) are an underexplored feature. I'm going to make void* no longer implicitly cast to T*, because ntrel is right, but in the long run I could envision something like *per-package* settings that adjust the way the language works. Pick and choose.

**Comment by FeepingCreature** [comment]
The deeper reasoning behind this is that pointer types imply a commitment, and the compiler should not sign the developer up to type-level commitments without their knowledge.

**Comment by FeepingCreature** [comment]
Changed, will be in next release.
