### ISSUE TITLE
File to build due to git@github.com: Permission denied (publickey).

### ISSUE THREAD

**Issue by mingodad** [Neat-Lang/neat#9]
When I try to build this project I'm getting this error:
```
neat$ make
./bootstrap.sh
Cloning into '.'...
done.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:funkwerk/boilerplate.git' into submodule path 'neat/build/f65eb856f00b3016025b105c4475b1b9c623bdf3/include/boilerplate' failed
Failed to clone 'include/boilerplate'. Retry scheduled
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:funkwerk/boilerplate.git' into submodule path 'neat/build/f65eb856f00b3016025b105c4475b1b9c623bdf3/include/boilerplate' failed
Failed to clone 'include/boilerplate' a second time, aborting
Makefile:4: recipe for target 'build/neat' failed
make: *** [build/neat] Error 1
```

**Comment by mingodad** [comment]
I just read the https://neat-lang.github.io/getstarted.html and found that I should use `build.sh` and in doing so it does build, so I'm closing this issue, although would be nice to know why `make` fails with the above message.

**Comment by FeepingCreature** [comment]
That's very strange!

1. The Makefile just calls build.sh, it's just there for kdevelop compatibility
2. build.sh shouldn't do anything involving ssh clones
3. include/boilerplate hasn't been required for years.

Are you sure you're building from current master?

**Comment by mingodad** [comment]
Thank you for reply !
Yes you are wright I was not on the current master, somehow it got out of sync.

**Comment by FeepingCreature** [comment]
Happens to everyone. :)

**Comment by mingodad** [comment]
But now when I try to build I'm getting this error message:
```
$ gcc -rdynamic .obj/83AC3451E5EDBFAE.o .obj/CAC279D79BAB560.o ... .obj/hash_5384FBA51A6FCC6F.c .obj/_run_unittests.c neat/.cache/bootstrap/v0.1.9/neat-v0.1.9-gcc/src/runtime.c -o build/neat_stage1 -ldl -Lclang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-18.04/lib -lLLVM -lm -lpthread
neat/.cache/bootstrap/v0.1.9/neat-v0.1.9-gcc/src/runtime.c:134:49: warning: ‘optnone’ attribute directive ignored [-Wattributes]
  134 | bool neat_runtime_symbol_defined_in_main(struct String symbol) {
      |                                                 ^~~~~~
/usr/bin/ld: cannot find -lLLVM
collect2: error: ld returned 1 exit status
command failed with 256
Assertion failed! Aborting.
```
I do not have any -lLLVM on my clang-14 downloaded from https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.0/clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz it's a bit outdated but it should be the full distribution.

**Comment by FeepingCreature** [comment]
Hmhm. What's your distro? There might be a separate package for the LLVM libs. Or you can use the gcc distro; that one doesn't use LLVM at all.

**Comment by mingodad** [comment]
I'm trying to build from a cloned repository and getting the above problems, downloading the https://github.com/Neat-Lang/neat/releases/download/v0.1.9/neat-v0.1.9-gcc.tar.xz then it builds, notice that there is a `src/main` binary there that when trying to execute gives this (on Ubuntu 18.04 64bits):
```
./main
./main: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./main)
```
Does that binary need to be there ?

**Comment by FeepingCreature** [comment]
Oh that's not good. That's definitely not supposed to be in there. Could you raise a new issue for that please?
